// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiauzRxC0h00_h0IDP_9pQaHowZ-YuIW0',
    appId: '1:436686686019:web:18a4bc0e24aad7c9eed1f6',
    messagingSenderId: '436686686019',
    projectId: 'veon-fashion-store',
    authDomain: 'veon-fashion-store.firebaseapp.com',
    storageBucket: 'veon-fashion-store.firebasestorage.app',
    measurementId: 'G-K3CEG4E2X6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2Oe2PNNm9DfYm0q2VTmalPklaz4Yzo9Y',
    appId: '1:436686686019:android:9cd9c3dd9587d449eed1f6',
    messagingSenderId: '436686686019',
    projectId: 'veon-fashion-store',
    storageBucket: 'veon-fashion-store.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBh3q8gTdotIhPqUlj4lS7hjClhHB2Bsdg',
    appId: '1:436686686019:ios:11765ab68df2c183eed1f6',
    messagingSenderId: '436686686019',
    projectId: 'veon-fashion-store',
    storageBucket: 'veon-fashion-store.firebasestorage.app',
    androidClientId: '436686686019-1j752kv7kdedv5ep2cjkm8hjjm1udg00.apps.googleusercontent.com',
    iosClientId: '436686686019-q56ds6f1fdbdi8gr40912aa1n59ubag6.apps.googleusercontent.com',
    iosBundleId: 'com.example.fashionStoreMobileApplicationProject01',
  );

}